export const letterMap = {
  a: "/App_9/letters/A.svg",
  b: "/App_9/letters/B.svg",
  c: "/App_9/letters/C.svg",
  d: "/App_9/letters/D.svg",
  e: "/App_9/letters/E.svg",
  f: "/App_9/letters/F.svg",
  g: "/App_9/letters/G.svg",
  h: "/App_9/letters/H.svg",
  i: "/App_9/letters/I.svg",
  j: "/App_9/letters/J.svg",
  k: "/App_9/letters/K.svg",
  l: "/App_9/letters/L.svg",
  m: "/App_9/letters/M.svg",
  n: "/App_9/letters/N.svg",
  o: "/App_9/letters/O.svg",
  p: "/App_9/letters/P.svg",
  q: "/App_9/letters/Q.svg",
  r: "/App_9/letters/R.svg",
  s: "/App_9/letters/S.svg",
  t: "/App_9/letters/T.svg",
  u: "/App_9/letters/U.svg",
  v: "/App_9/letters/V.svg",
  w: "/App_9/letters/W.svg",
  x: "/App_9/letters/X.svg",
  y: "/App_9/letters/Y.svg",
  z: "/App_9/letters/Z.svg",
};
